/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

package main

import "fmt"

func main() {
    fibArray, sum, i := [...]int{0,1}, 0, 1

    for i <= 4e6 {
        fibArray[0] = fibArray[1]
        fibArray[1] = i
        
        i = fibArray[0] + fibArray[1]
        if i % 2 == 0 {
            sum += i
        }
    }

    fmt.Printf("Sum of even-valued terms in the Fibonacci sequence not exceeding 4,000,000 = %d\n", sum)
}
